# Generated by Django 3.2 on 2021-04-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('select', models.CharField(choices=[('高', '高'), ('中', '中'), ('低', '低')], max_length=1)),
                ('up_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-up_date',),
            },
        ),
    ]
